export const Colors = {
  primary: '#7C3AED',
  primaryDark: '#5B21B6',
  primaryLight: '#EDE9FE',
  primaryMuted: '#DDD6FE',
  background: '#FAFAFA',
  white: '#FFFFFF',
  textPrimary: '#1F2937',
  textSecondary: '#6B7280',
  textMuted: '#9CA3AF',
  inputBg: '#F3F4F6',
  inputBorder: '#E5E7EB',
  inputBorderFocus: '#7C3AED',
  success: '#22C55E',
  error: '#EF4444',
  securityBg: '#F5F3FF',
  shadow: '#7C3AED10',
  border: '#E5E7EB',
};
