services:
  - type: web
    name: paynova-api
    runtime: node
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && npx prisma migrate deploy && node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
    healthCheckPath: /external-api/status
